name: Cloudflare Purge

on:
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Purge Cloudflare cache
        run: ./cloudflare/purge-cache.sh
